### ISSUE TITLE
Fails to handle GetArchiveLink routes

### ISSUE THREAD

**Issue by edwardofclt** [migueleliasweb/go-github-mock#18]
Using the following logic (with a custom EndpointPattern because the already existing pattern assumes you're specifying a ref) I get an `Get "": unsupported protocol scheme ""` response.

```golang
mock.WithRequestMatchHandler(mock.EndpointPattern{
  Pattern: "/repos/{owner}/{repo}/zipball",
  Method:  "GET",
}, http.HandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
  rw.WriteHeader(http.StatusFound)
  rw.Header().Add("Location", "https://codeload.github.com/gothinkster/react-redux-realworld-example-app/legacy.zip/refs/heads/master")
})),
```

I'm unsure if what I'm doing is inherently wrong, but I believe I'm returning the same response that Github would return with the `http.StatusFound` response and with a header identifying the location of the requested zipball.

* * * 

Also, let me just say, I really appreciate this project - it's gotten me 95% of the way where I need to be for a project I'm working on. So, thank you!

**Comment by migueleliasweb** [comment]
Hi @edwardofclt , 

could you paste here the SDK method you're running?

**Comment by migueleliasweb** [comment]
I just noticed there is a possible improvement to the mock framework where the optional parameters are used to generate endpoints without them so the calls can succeed.

**Comment by migueleliasweb** [comment]
It appears, even the OpenApiSpec for the Github API says all parameters for the endpoint `/repos/{owner}/{repo}/zipball/{ref}` are required but the description explains otherwise :disappointed: . 

Even the `go-github` SDK handles it in a weird way by appending the `ref` if it's present. :disappointed: 


See: 

- https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.json?raw=true.
- https://github.com/google/go-github/blob/master/github/repos_contents.go#L284

This seems to be an edge case.

**Comment by edwardofclt** [comment]
No worries, I'm using the `GetArchiveLink` method. I noticed the same thing in the go-github package. Thought it was odd.

**Comment by edwardofclt** [comment]
@migueleliasweb about to sign off for the rest of the year - any tips on how to make this endpoint work?

**Comment by migueleliasweb** [comment]
I have an idea how to mitigate this but it will require some substantial changes to the internals of the way requests are configured in the mock server.

The main problem seems to be the expected HTTP status and header is quite specific for this endpoint.

I probably won't be able to have enough time to fix this today, I'm sorry.

If you have the time, feel free to raise a PR and I will be happy to review.

**Comment by migueleliasweb** [comment]
Hi @edwardofclt ,

I might have found a workaround. Can you try to use https://github.com/migueleliasweb/go-github-mock/pull/20 as see if it suits you?

**Comment by edwardofclt** [comment]
Awesome! Thanks, I'll give it a go soon.

**Comment by migueleliasweb** [comment]
@edwardofclt Any updates on this?

**Comment by migueleliasweb** [comment]
I will be closing this for now.
