### ISSUE TITLE
Unable to mock Git.GetRef

### ISSUE THREAD

**Issue by oba11** [migueleliasweb/go-github-mock#24]
I tried mocking `Git.GetRef` but unable to make it work

```
mockedHTTPClient := mock.NewMockedHTTPClient(
	mock.WithRequestMatch(
		mock.GetReposGitRefByOwnerByRepoByRef,
		github.Reference{},
	),
)
c := github.NewClient(mockedHTTPClient)
ctx := context.Background()

reference, resp, err := c.Git.GetRef(ctx, "foo", "bar", "main")
log.Println(reference)
log.Println(resp.Response.StatusCode)
log.Println(resp.Response.Request)

// time="2022-03-23T12:21:53+04:00" level=info msg="<nil>"
// time="2022-03-23T12:21:53+04:00" level=info msg=404
// time="2022-03-23T12:21:53+04:00" level=info msg="&{GET http://127.0.0.1:55565/repos/foo/bar/git/ref/main HTTP/1.1 1 1 map[Accept:[application/vnd.github.v3+json] User-Agent:[go-github]] <nil> <nil> 0 [] false api.github.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc00001c0b0}"
```

I tried similar mock with `c.Git.CreateRef` and works fine.
Anything I'm doing wrong that should be changed?

**Comment by migueleliasweb** [comment]
Hi @oba11 , could you try using `GetReposGitRefByOwnerByRepoByRef` instead?

By looking inside the go-github `GetRef()` definitions, looks like it's requesting `"repos/%v/%v/git/ref/%v"`. This URL doesn't match `PostReposGitRefsByOwnerByRepo` but it should work with `GetReposGitRefByOwnerByRepoByRef`.

:+1:

**Comment by oba11** [comment]
@migueleliasweb my apologies, it was a typo which I've corrected. I tried it with `GetReposGitRefByOwnerByRepoByRef` but didn't seem to work

**Comment by migueleliasweb** [comment]
I will have a better look soon, @oba11 .

**Comment by migueleliasweb** [comment]
Hi @oba11 , could you check for me if your problem is similar to this one? https://github.com/migueleliasweb/go-github-mock/issues/26#issuecomment-1080465128

**Comment by oba11** [comment]
@migueleliasweb yes you are right, I just tested https://github.com/migueleliasweb/go-github-mock@allow-extended-last-parameters and it works. Thanks alot

**Comment by migueleliasweb** [comment]
Closing in favour of https://github.com/migueleliasweb/go-github-mock/issues/26

**Comment by oba11** [comment]
Thank you
