### ISSUE TITLE
Question: how to sponsor this project?

### ISSUE THREAD

**Issue by marcelosousa** [migueleliasweb/go-github-mock#31]
Hi 👋 , 

Thanks so much for the work on this project! At @Reviewpad, we are trying to support the OSS projects that we use as dependencies to our main repository [reviewpad/reviewpad](https://github.com/reviewpad/reviewpad). 

Do you plan to join any sponsoring program? We are also happy to help the community to maintain the project.

Thanks!

**Comment by migueleliasweb** [comment]
Hi @marcelosousa , I'm gonna be honest I haven't thought of this. Maybe this could be interesting! Are you talking about sponsoring a project like in https://github.com/sponsors?

**Comment by marcelosousa** [comment]
Yes, that would be the easiest. We can also help in other ways if you need any assistance with issues, code reviews or development.

**Comment by migueleliasweb** [comment]
Hi @marcelosousa, any help with issues or development is welcomed - with or without sponsoring. Feel welcomed to contribute. I will be happy to review the purposed code :).

**Comment by marcelosousa** [comment]
Sounds good @migueleliasweb ! Let us know if you do sign up for the sponsorship program 👍
