### ISSUE TITLE
Deprecated gorilla

### ISSUE THREAD

**Issue by kwk** [migueleliasweb/go-github-mock#49]
Hi, 

Thank you for this project!!!

I've been using this project for mocking github responses and I wonder if you have considered switching to something other than gorilla. It was deprecated:

> The Gorilla project has been archived, and is no longer under active maintainenance. You can read more here: https://github.com/gorilla#gorilla-toolkit

**Comment by migueleliasweb** [comment]
Hi @kwk , 

Yeah I'm aware of that. When I saw they set that whole project as "archived" I considerd moving away from using it. 

For now, I don't think there is a pressing need to do it but at some point in the near-ish future, we could change to some other router.
