### ISSUE TITLE
Go cannot resolve latest release

### ISSUE THREAD

**Issue by mlschechter** [migueleliasweb/go-github-mock#70]
When I try to update to `v0.1`, I get the following error:

```
michael.schechter@mschechter-mbp idp-core-worker % go mod tidy -v    
go: errors parsing go.mod:
go.mod:14:2: no matching versions for query "v0.1"
```

`go.mod` content:

```
	github.com/migueleliasweb/go-github-mock v0.1
```

Does the version need to be published somewhere in order to be consumable?

**Comment by migueleliasweb** [comment]
Hi @mlschechter , I had created a tag that wasn't quite `semver`. I just pushed the correct tag `v1.0.0` and updated the release. Please have a look.

**Comment by mlschechter** [comment]
Thanks for the quick resolution - I'll take a look on Monday!

**Comment by mlschechter** [comment]
Looks good - thanks!
